import XCTest
import AppKit
@testable import DayLineCore

final class DayLineCoreTests: XCTestCase {
    private var calendar: Calendar { var c=Calendar(identifier:.gregorian); c.timeZone=TimeZone(identifier:"America/Los_Angeles")!; return c }
    private func date(_ day:Int,_ hour:Int,_ minute:Int,_ second:Int=0)->Date { calendar.date(from:DateComponents(year:2026,month:9,day:day,hour:hour,minute:minute,second:second))! }
    private func event(_ id:Int64,_ start:Date,_ end:Date)->CalendarEvent { CalendarEvent(id:id,title:"事件 \(id)",startsAt:start,endsAt:end) }
    func testMinutePositionAndCrossDayClip() { let day=date(7,0,0); let e=event(1,date(6,23,30),date(8,1,15)); XCTAssertEqual(TimelineLayout.minute(TimelineLayout.clip(e,to:day,calendar:calendar)!.start,on:day,calendar:calendar),0); XCTAssertEqual(TimelineLayout.minute(TimelineLayout.clip(e,to:day,calendar:calendar)!.end,on:day,calendar:calendar),1440); XCTAssertNil(TimelineLayout.clip(event(2,date(6,23,0),date(7,0,0)),to:day,calendar:calendar)) }
    func testQuarterHourSelectionIsBidirectionalAndEndsAt24() { XCTAssertEqual(TimelineLayout.selection(from:547,to:622).0,540); XCTAssertEqual(TimelineLayout.selection(from:547,to:622).1,630); XCTAssertEqual(TimelineLayout.selection(from:622,to:547).0,540); XCTAssertEqual(TimelineLayout.selection(from:1438,to:1440).0,1425); XCTAssertEqual(TimelineLayout.timeText(1440),"24:00") }
    func testShortEventsParticipateInOverlapColumns() { let d=date(7,0,0); let p=TimelineLayout.placements([event(1,date(7,15,0),date(7,15,5)),event(2,date(7,15,20),date(7,15,25))],on:d,calendar:calendar); XCTAssertEqual(p.map(\.columns),[2,2]); XCTAssertEqual(p.map(\.column),[0,1]) }
    func testConnectedOverlapAndEndpointReuse() { let d=date(7,0,0); let p=TimelineLayout.placements([event(1,date(7,9,0),date(7,10,0)),event(2,date(7,9,30),date(7,11,0)),event(3,date(7,10,30),date(7,12,0))],on:d,calendar:calendar); XCTAssertEqual(p.map(\.columns),[2,2,2]); XCTAssertEqual(p.map(\.column),[0,1,0]); let touching=TimelineLayout.placements([event(4,date(7,13,0),date(7,14,0)),event(5,date(7,14,0),date(7,15,0))],on:d,calendar:calendar); XCTAssertEqual(touching.map(\.columns),[1,1]) }
    func testStoreReminderRulesAndNotesOnlyEditPreservesSnooze() throws { let dir=URL(fileURLWithPath:NSTemporaryDirectory()).appendingPathComponent(UUID().uuidString); defer { try? FileManager.default.removeItem(at:dir) }; let store=try EventStore(path:dir.appendingPathComponent("events.db")); let now=date(7,9,0); let e=try store.add(title:"未来",startsAt:date(7,10,0),endsAt:date(7,11,0),notes:"n",now:now); XCTAssertNil(e.alertedAt); try store.snooze(e.id,now:now); let snoozed=try store.get(e.id)!; _=try store.update(id:e.id,title:"未来改名",startsAt:e.startsAt,endsAt:e.endsAt,notes:"备注",now:now); XCTAssertEqual(try store.get(e.id)!.reminderAt,snoozed.reminderAt); let past=try store.add(title:"过去",startsAt:date(7,8,0),endsAt:date(7,8,30),now:now); XCTAssertNotNil(past.alertedAt); try store.complete(e.id,completed:true,now:now); try store.complete(e.id,completed:false,now:now); XCTAssertNil(try store.get(e.id)!.alertedAt) }
    func testSettingsUsesDefaultsForPartialOrInvalidFile() throws { let url=URL(fileURLWithPath:NSTemporaryDirectory()).appendingPathComponent(UUID().uuidString); try "{\"theme_color\":\"bad\",\"font_scale\":99}".data(using:.utf8)!.write(to:url); let settings=SettingsStore(path:url).current; XCTAssertEqual(settings.themeColor,"#28735f"); XCTAssertEqual(settings.fontScale,1); XCTAssertEqual(settings.desktopTheme,"dark"); XCTAssertEqual(settings.bgColor,"#1e242b"); XCTAssertEqual(settings.bgOpacity,0.90); XCTAssertEqual(settings.bgType,"color"); XCTAssertEqual(settings.bgImagePath,"") }
    func testBackgroundSettingsCustomizationAndPersistence() throws { let url=URL(fileURLWithPath:NSTemporaryDirectory()).appendingPathComponent(UUID().uuidString); let store=SettingsStore(path:url); var s=store.current; s.bgColor="#2d3748"; s.bgOpacity=0.75; s.bgType="image"; s.bgImagePath="/Users/holixxx/Downloads/science_gate.png"; try store.save(s); let loaded=SettingsStore(path:url).current; XCTAssertEqual(loaded.bgColor,"#2d3748"); XCTAssertEqual(loaded.bgOpacity,0.75); XCTAssertEqual(loaded.bgType,"image"); XCTAssertEqual(loaded.bgImagePath,"/Users/holixxx/Downloads/science_gate.png") }
    func testScienceGateImageFileLoading() throws {
        let path = "/Users/holixxx/Downloads/science_gate.png"
        guard FileManager.default.fileExists(atPath: path) else { return }
        let image = NSImage(contentsOfFile: path)
        XCTAssertNotNil(image)
        XCTAssertGreaterThan(image?.size.width ?? 0, 0)
        XCTAssertGreaterThan(image?.size.height ?? 0, 0)
    }
    func testCRUDAndReopenPersistence() throws { let dir=URL(fileURLWithPath:NSTemporaryDirectory()).appendingPathComponent(UUID().uuidString); defer { try? FileManager.default.removeItem(at:dir) }; let path=dir.appendingPathComponent("events.db"); let store=try EventStore(path:path); let created=try store.add(title:"原名称",startsAt:date(7,10,0),endsAt:date(7,11,0),notes:"旧备注",now:date(7,9,0)); let updated=try store.update(id:created.id,title:"新名称",startsAt:date(7,10,30),endsAt:date(7,11,30),notes:"新备注",now:date(7,9,0)); XCTAssertEqual(updated.title,"新名称"); XCTAssertEqual(updated.notes,"新备注"); XCTAssertEqual(try EventStore(path:path).get(created.id)?.title,"新名称"); try store.delete(created.id); XCTAssertNil(try store.get(created.id)) }
    func testDueSnoozeAlertAndExpiryBoundaries() throws { let dir=URL(fileURLWithPath:NSTemporaryDirectory()).appendingPathComponent(UUID().uuidString); defer { try? FileManager.default.removeItem(at:dir) }; let path=dir.appendingPathComponent("events.db"); let store=try EventStore(path:path); let now=date(7,12,0); let createdAt=date(5,9,0); let due=try store.add(title:"到点",startsAt:now.addingTimeInterval(-60),endsAt:now.addingTimeInterval(3600),now:createdAt); let boundary=try store.add(title:"24小时边界",startsAt:now.addingTimeInterval(-86_400),endsAt:now.addingTimeInterval(-85_000),now:createdAt); let stale=try store.add(title:"过期",startsAt:now.addingTimeInterval(-86_401),endsAt:now.addingTimeInterval(-86_000),now:createdAt); XCTAssertEqual(try store.due(now:now).map(\.id),[boundary.id,due.id]); XCTAssertEqual(try store.expireStale(now:now),1); try store.markAlerted(due.id,now:now); let reopenedAfterAlert=try EventStore(path:path); XCTAssertFalse(try reopenedAfterAlert.due(now:now).map(\.id).contains(due.id)); try store.snooze(due.id,minutes:10,now:now); let reopenedAfterSnooze=try EventStore(path:path); XCTAssertEqual(try reopenedAfterSnooze.get(due.id)?.reminderAt,now.addingTimeInterval(600)); XCTAssertEqual(try reopenedAfterSnooze.due(now:now.addingTimeInterval(599)).count,0); XCTAssertTrue(try reopenedAfterSnooze.due(now:now.addingTimeInterval(600)).map(\.id).contains(due.id)); XCTAssertNotNil(try store.get(stale.id)?.alertedAt) }
}
