#!/bin/zsh
set -euo pipefail
base_dir="${0:A:h:h}"
cd "$base_dir"
app_version="${DAYLINE_VERSION:-1.0.0}"
build_version="${DAYLINE_BUILD_VERSION:-1}"
if [[ "$app_version" == "1.0.0" ]]; then
  release_tag="${DAYLINE_RELEASE_TAG:-Macos_version}"
else
  release_tag="${DAYLINE_RELEASE_TAG:-v$app_version}"
fi
SWIFTPM_MODULECACHE_OVERRIDE="$base_dir/.build/module-cache" CLANG_MODULE_CACHE_PATH="$base_dir/.build/clang-module-cache" swift build -c release --scratch-path "$base_dir/.build"
app="$base_dir/build/DayLine.app"
# This is an explicitly fixed, generated path under macos/build.
rm -rf "$app"
mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"
cp "$base_dir/.build/release/DayLine" "$app/Contents/MacOS/DayLine"
cp "$base_dir/.build/release/DayLineUpdaterHelper" "$app/Contents/Resources/DayLineUpdaterHelper"
cp "$base_dir/Resources/DayLine.icns" "$app/Contents/Resources/DayLine.icns"
cp "$base_dir/Info.plist" "$app/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $app_version" "$app/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $build_version" "$app/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :DLCurrentReleaseTag $release_tag" "$app/Contents/Info.plist"
xattr -cr "$app"
codesign --force --deep --sign - "$app"
codesign --verify --deep --strict "$app"
COPYFILE_DISABLE=1 ditto -c -k --norsrc --keepParent "$app" "$base_dir/build/DayLine-macOS.zip"
shasum -a 256 "$base_dir/build/DayLine-macOS.zip" > "$base_dir/build/DayLine-macOS.zip.sha256"
cp "$base_dir/build/DayLine-macOS.zip" "$base_dir/build/DayLine.app.zip"
repo_dir="$(cd "$base_dir/.." && pwd)"
mkdir -p "$repo_dir/dist"
cp "$base_dir/build/DayLine-macOS.zip" "$repo_dir/dist/DayLine-macOS.zip"
cp "$base_dir/build/DayLine-macOS.zip.sha256" "$repo_dir/dist/DayLine-macOS.zip.sha256"
echo "已生成：$app"
echo "可分发的无扩展属性包："
echo "  - $base_dir/build/DayLine-macOS.zip"
echo "  - $repo_dir/dist/DayLine-macOS.zip"
echo "版本：$app_version（$release_tag），构建号：$build_version"
